linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - misspell
    - revive
    - unconvert
    - unparam
    - whitespace

linters-settings:
  govet:
    enable:
      - shadow
  revive:
    min-confidence: 0.8

issues:
  exclude-dirs:
    - docs
    - vendor
    - bin
  exclude-rules:
    - linters:
        - revive
      text: unexported-return