version: "2"

linters:
  default: none
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - revive
    - unconvert
    - unparam
    - whitespace
  settings:
    govet:
      enable:
        - shadow
    revive:
      confidence: 0.8
  exclusions:
    generated: lax
    paths:
      - docs
      - vendor
      - bin
    rules:
      - linters:
          - revive
        text: unexported-return

formatters:
  enable:
    - gofmt
    - goimports