services:
  auth-db:
    image: postgres:15-alpine
    container_name: auth-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports: 
      - "5432:5432"
    volumes:
      - auth-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - messenger-network

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=auth_db 
      - DB_HOST=auth-db 
      - DB_PORT=5432   
      - JWT_SECRET=secret
      - SERVER_PORT=:8080
    depends_on:
      auth-db:
        condition: service_healthy
    networks:
      - messenger-network

  chat-db:
    image: postgres:15-alpine
    container_name: chat-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat_db
    ports:
      - "5433:5432"  
    volumes:
      - chat-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - messenger-network

  chat-service:
    build:
      context: ./chat-service
      dockerfile: Dockerfile
    container_name: chat-service
    ports:
      - "8081:8081"
    environment:
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=chat_db 
      - DB_HOST=chat-db 
      - DB_PORT=5432    
      - JWT_SECRET=secret
      - SERVER_PORT=:8081
    depends_on:
      chat-db:
        condition: service_healthy
    networks:
      - messenger-network


volumes: 
  auth-pgdata:
  chat-pgdata:

networks:
  messenger-network:
    driver: bridge