.PHONY: up down build test lint

up:
	docker compose up --build -d

down:
	docker compose down

build:
	docker compose build

test:
	cd auth-service && go test ./...
	cd chat-service && go test ./...
	cd notification-service && go test ./...
	cd api-gateway && go test ./...

lint:
	cd auth-service && golangci-lint run ./...
	cd chat-service && golangci-lint run ./...
	cd notification-service && golangci-lint run ./...
	cd api-gateway && golangci-lint run ./...
